development:
  adapter: postgresql
  encoding: unicode
  database: lunchhaus_development
  username: lunchhaus
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: lunchhaus_test
  username: lunchhaus
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: lunchhaus_production
  username: lunchhaus
  pool: 5
